export const FETCH_LIST_CINEMA_REQUEST = "Datve/DatveReducer/FETCH_LIST_CINEMA_REQUEST"
export const FETCH_LIST_CINEMA_SUCCESS = "Datve/DatveReducer/FETCH_LIST_CINEMA_SUCCESS"
export const FETCH_LIST_CINEMA_FAILED = "Datve/DatveReducer/FETCH_LIST_CINEMA_FAILED"